export enum DayForecastKeys {
  MaxTempC = 'maxtemp_c',
  MaxTempF = 'maxtemp_f',
  MinTempC = 'mintemp_c',
  MinTempF = 'mintemp_f',
  AvgTempC = 'avgtemp_c',
  AvgTempF = 'avgtemp_f',
  MaxWindMph = 'maxwind_mph',
  MaxWindKph = 'maxwind_kph',
  TotalPrecipMm = 'totalprecip_mm',
  TotalPrecipIn = 'totalprecip_in',
  TotalSnowCm = 'totalsnow_cm',
  AvgVisKm = 'avgvis_km',
  AvgVisMiles = 'avgvis_miles',
  AvgHumidity = 'avghumidity',
  DailyWillItRain = 'daily_will_it_rain',
  DailyChanceOfRain = 'daily_chance_of_rain',
  DailyWillItSnow = 'daily_will_it_snow',
  DailyChanceOfSnow = 'daily_chance_of_snow',
  Condition = 'condition',
  UV = 'uv',
}

export enum CurrentWeatherKeys {
  LastUpdatedEpoch = 'last_updated_epoch',
  LastUpdated = 'last_updated',
  TempC = 'temp_c',
  TempF = 'temp_f',
  IsDay = 'is_day',
  Condition = 'condition',
  WindMph = 'wind_mph',
  WindKph = 'wind_kph',
  WindDegree = 'wind_degree',
  WindDir = 'wind_dir',
  PressureMb = 'pressure_mb',
  PressureIn = 'pressure_in',
  PrecipMm = 'precip_mm',
  PrecipIn = 'precip_in',
  Humidity = 'humidity',
  Cloud = 'cloud',
  FeelsLikeC = 'feelslike_c',
  FeelsLikeF = 'feelslike_f',
  WindChillC = 'windchill_c',
  WindChillF = 'windchill_f',
  HeatIndexC = 'heatindex_c',
  HeatIndexF = 'heatindex_f',
  DewPointC = 'dewpoint_c',
  DewPointF = 'dewpoint_f',
  VisKm = 'vis_km',
  VisMiles = 'vis_miles',
  UV = 'uv',
  GustMph = 'gust_mph',
  GustKph = 'gust_kph'
}